version: '3.8'
services:
  db:
    container_name: product-api-db
    image: mongo:latest
    volumes:
      - db_data:/data/db
    restart: always
    ports:
      - '27017:27017'
  redis:
    container_name: product-api-redis
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
  product-api:
    container_name: product-api
    depends_on:
      - redis
      - db
    restart: always
    build: .
    image: dayvsonsales/product-api
    ports:
      - '3333:3333'
    environment:
      NODE_ENV: production
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CACHE_RESET_TIME: 1800
      MONGO_CONNECTION: mongodb://db/products_db
volumes:
  db_data: {}
